api/urls.py
from django.urls import path, include

from . import views

app_name = 'api'

urlpatterns = [
    #path('', views.IndexView.as_view()),
    path('categoria', views.CategoriaView.as_view()),
    path('producto', views.ProductoView.as_view()),
    path('categoria/<int:pk>/', views.CategoriaDetailView.as_view()),
    path('producto/<int:pk>/', views.ProductoDetailView.as_view()),
]

# from rest_framework.routers import DefaultRouter
# router = DefaulRouter()
# router.register(r'producto', view.ProductoViewSet, basename='producto')
# path('admin/', include(router.urls)),

lab06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tienda/', include('tienda.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:producto_id>/', views.producto, name='producto'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
]

api/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha de registro',auto_now=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre

api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics

from tienda.models import Categoria, Producto
from .serializers import CategoriaSerializer, ProductoSerializer

# class IndexView(APIView):
#     def get(self, request):
#         lista_categorias = Categoria.objects.all()
#         serializer_categoria = CategoriaSerializer(lista_categorias, many=True)
#         return Response(serializer_categoria.data)

class CategoriaView(generics.ListCreateAPIView):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

class CategoriaDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

class ProductoView(generics.ListCreateAPIView):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

class ProductoDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

# from rest_framework import viewsets
# class ProductoViewSet(viewsets.ModelViewSet)
#   queryset = Producto.objects.all()
#   serializer_class = ProductoSerializer

tienda/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Producto
from .models import Categoria

def index(request):
    #produc_list = Producto.objects.order_by('nombre')[:6]
    product_list = Producto.objects.all()
    category_list = Categoria.objects.all()
    context = {
        'productos': product_list,
        'categorias': category_list
    }
    return render(request, 'index.html', context)

def producto(request, producto_id):
    producto = get_object_or_404(Producto, pk = producto_id)
    category_list = Categoria.objects.all()
    context = {
        'productos': producto,
        'categorias': category_list,
    }
    return render(request,'producto.html', context)

def categoria(request, categoria_id):
    category = get_object_or_404(Categoria, pk=categoria_id)
    product_list = Producto.objects.filter(categoria=category)
    category_list = Categoria.objects.all()
    context = {
        'productos': product_list,
        'categorias': category_list,
    }
    return render(request, 'index.html', context)

tienda/templates/index.html
{% extends 'layout.html' %} {% block content %}


<div
id="carouselExampleIndicators"
class="carousel slide my-4"
data-ride="carousel"
>
<ol class="carousel-indicators">
  <li
    data-target="#carouselExampleIndicators"
    data-slide-to="0"
    class="active"
  ></li>
  <li
    data-target="#carouselExampleIndicators"
    data-slide-to="1"
  ></li>
  <li
    data-target="#carouselExampleIndicators"
    data-slide-to="2"
  ></li>
</ol>
<div class="carousel-inner" role="listbox">
  <div class="carousel-item active">
    <img
      class="d-block img-fluid"
      src="http://placehold.it/900x350"
      alt="First slide"
    />
  </div>
  <div class="carousel-item">
    <img
      class="d-block img-fluid"
      src="http://placehold.it/900x350"
      alt="Second slide"
    />
  </div>
  <div class="carousel-item">
    <img
      class="d-block img-fluid"
      src="http://placehold.it/900x350"
      alt="Third slide"
    />
  </div>
</div>
<a
  class="carousel-control-prev"
  href="#carouselExampleIndicators"
  role="button"
  data-slide="prev"
>
  <span
    class="carousel-control-prev-icon"
    aria-hidden="true"
  ></span>
  <span class="sr-only">Previous</span>
</a>
<a
  class="carousel-control-next"
  href="#carouselExampleIndicators"
  role="button"
  data-slide="next"
>
  <span
    class="carousel-control-next-icon"
    aria-hidden="true"
  ></span>
  <span class="sr-only">Next</span>
</a>
</div>


    <div class="row">
      {% for prod in productos %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <a href="{% url 'tienda:producto' prod.id %}"
            ><img class="card-img-top" src="http://placehold.it/700x400" alt=""
          /></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{% url 'tienda:producto' prod.id %}">{{ prod.nombre }}</a>
            </h4>
            <h5>S/. {{ prod.precio}}</h5>
            <p class="card-text">Categoria: {{ prod.categoria.nombre }}</p>
          </div>
          <div class="card-footer">
            <small class="text-muted"
              >&#9733; &#9733; &#9733; &#9733; &#9734;</small
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>



{% endblock %}

tienda/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Shop Homepage</title>
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'css/shop.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#" >Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for cat in categorias %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tienda:categoria' cat.id %}">{{ cat.nombre }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->

    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <h1 class="my-4">Categorias</h1>
          <div class="list-group">
            {% for cat in categorias %}
            <a href="{% url 'tienda:categoria' cat.id %}" class="list-group-item">
              {{ cat.nombre }}
            </a>
            {% endfor %}
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
          <!-- Block Content -->


          {% block content %} {% endblock %}

          <!-- /Block Content -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->

    <br><br><br><br><br><br><br>
    <!-- Footer -->
    <footer class="py-5 bg-dark fixed-bottom">
      <div class="container">
        <p class="m-0 text-center text-white">
          Copyright &copy; Your Website 2023 YNRH
        </p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

tienda/templates/producto.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-4">Detalle de producto</h1>

    <div class="producto">
        <h3 class="mb-3">Producto: {{ productos.nombre }}</h3>
        <p class="mb-2">Precio: {{ productos.precio }}</p>
        <p class="mb-2">Stock: {{ productos.stock }}</p>
        <p class="mb-2">Categoría: {{ productos.categoria.nombre }}</p>
    </div>
    <a class="btn btn-primary mt-4" href="/tienda/">Volver</a>

{% endblock %}